/* Auto-generated by genmsg_cpp for file /nishome/gcerna/ros/rosbuild_ws/taskallocator/msg/Bid.msg */
#ifndef TASKALLOCATOR_MESSAGE_BID_H
#define TASKALLOCATOR_MESSAGE_BID_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"
#include "taskallocator/Instruction.h"

namespace taskallocator
{
template <class ContainerAllocator>
struct Bid_ {
  typedef Bid_<ContainerAllocator> Type;

  Bid_()
  : header()
  , inst()
  , bidCost(0.0)
  {
  }

  Bid_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , inst(_alloc)
  , bidCost(0.0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef  ::taskallocator::Instruction_<ContainerAllocator>  _inst_type;
   ::taskallocator::Instruction_<ContainerAllocator>  inst;

  typedef float _bidCost_type;
  float bidCost;


  typedef boost::shared_ptr< ::taskallocator::Bid_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::taskallocator::Bid_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Bid
typedef  ::taskallocator::Bid_<std::allocator<void> > Bid;

typedef boost::shared_ptr< ::taskallocator::Bid> BidPtr;
typedef boost::shared_ptr< ::taskallocator::Bid const> BidConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::taskallocator::Bid_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::taskallocator::Bid_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace taskallocator

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::taskallocator::Bid_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::taskallocator::Bid_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::taskallocator::Bid_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d550354f9161d53878b35fcb15499a4f";
  }

  static const char* value(const  ::taskallocator::Bid_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd550354f9161d538ULL;
  static const uint64_t static_value2 = 0x78b35fcb15499a4fULL;
};

template<class ContainerAllocator>
struct DataType< ::taskallocator::Bid_<ContainerAllocator> > {
  static const char* value() 
  {
    return "taskallocator/Bid";
  }

  static const char* value(const  ::taskallocator::Bid_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::taskallocator::Bid_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
Instruction inst\n\
float32 bidCost\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: taskallocator/Instruction\n\
Header header\n\
uint32 ID\n\
uint32 startFloor\n\
float32 startX\n\
float32 startY\n\
uint32 endFloor\n\
float32 endX\n\
float32 endY\n\
\n\
";
  }

  static const char* value(const  ::taskallocator::Bid_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::taskallocator::Bid_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::taskallocator::Bid_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::taskallocator::Bid_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.inst);
    stream.next(m.bidCost);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Bid_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::taskallocator::Bid_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::taskallocator::Bid_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "inst: ";
s << std::endl;
    Printer< ::taskallocator::Instruction_<ContainerAllocator> >::stream(s, indent + "  ", v.inst);
    s << indent << "bidCost: ";
    Printer<float>::stream(s, indent + "  ", v.bidCost);
  }
};


} // namespace message_operations
} // namespace ros

#endif // TASKALLOCATOR_MESSAGE_BID_H

