/* Auto-generated by genmsg_cpp for file /nishome/gcerna/ros/rosbuild_ws/taskallocator/msg/Instruction.msg */
#ifndef TASKALLOCATOR_MESSAGE_INSTRUCTION_H
#define TASKALLOCATOR_MESSAGE_INSTRUCTION_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace taskallocator
{
template <class ContainerAllocator>
struct Instruction_ {
  typedef Instruction_<ContainerAllocator> Type;

  Instruction_()
  : header()
  , reqsHumanHelp(false)
  , helpDescriptor()
  , startFloor(0)
  , startX(0.0)
  , startY(0.0)
  , endFloor(0)
  , endX(0.0)
  , endY(0.0)
  {
  }

  Instruction_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , reqsHumanHelp(false)
  , helpDescriptor(_alloc)
  , startFloor(0)
  , startX(0.0)
  , startY(0.0)
  , endFloor(0)
  , endX(0.0)
  , endY(0.0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef uint8_t _reqsHumanHelp_type;
  uint8_t reqsHumanHelp;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _helpDescriptor_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  helpDescriptor;

  typedef uint32_t _startFloor_type;
  uint32_t startFloor;

  typedef float _startX_type;
  float startX;

  typedef float _startY_type;
  float startY;

  typedef uint32_t _endFloor_type;
  uint32_t endFloor;

  typedef float _endX_type;
  float endX;

  typedef float _endY_type;
  float endY;


  typedef boost::shared_ptr< ::taskallocator::Instruction_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::taskallocator::Instruction_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Instruction
typedef  ::taskallocator::Instruction_<std::allocator<void> > Instruction;

typedef boost::shared_ptr< ::taskallocator::Instruction> InstructionPtr;
typedef boost::shared_ptr< ::taskallocator::Instruction const> InstructionConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::taskallocator::Instruction_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::taskallocator::Instruction_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace taskallocator

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::taskallocator::Instruction_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::taskallocator::Instruction_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::taskallocator::Instruction_<ContainerAllocator> > {
  static const char* value() 
  {
    return "c5b8fd0efb48ef4c6ae166244ce8dd59";
  }

  static const char* value(const  ::taskallocator::Instruction_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xc5b8fd0efb48ef4cULL;
  static const uint64_t static_value2 = 0x6ae166244ce8dd59ULL;
};

template<class ContainerAllocator>
struct DataType< ::taskallocator::Instruction_<ContainerAllocator> > {
  static const char* value() 
  {
    return "taskallocator/Instruction";
  }

  static const char* value(const  ::taskallocator::Instruction_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::taskallocator::Instruction_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
\n\
#determines type of instruction\n\
bool reqsHumanHelp\n\
\n\
#standardized set of descriptors for different human interactions (eventually)\n\
#extraneous if reqsHumanHelp is false\n\
#not yet implemented (only goto is right now) \n\
string helpDescriptor\n\
\n\
#all fields below are only for goto commands\n\
#extraneous if reqsHumanHelp is true\n\
uint32 startFloor\n\
float32 startX\n\
float32 startY\n\
\n\
uint32 endFloor\n\
float32 endX\n\
float32 endY\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::taskallocator::Instruction_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::taskallocator::Instruction_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::taskallocator::Instruction_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::taskallocator::Instruction_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.reqsHumanHelp);
    stream.next(m.helpDescriptor);
    stream.next(m.startFloor);
    stream.next(m.startX);
    stream.next(m.startY);
    stream.next(m.endFloor);
    stream.next(m.endX);
    stream.next(m.endY);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Instruction_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::taskallocator::Instruction_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::taskallocator::Instruction_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "reqsHumanHelp: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.reqsHumanHelp);
    s << indent << "helpDescriptor: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.helpDescriptor);
    s << indent << "startFloor: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.startFloor);
    s << indent << "startX: ";
    Printer<float>::stream(s, indent + "  ", v.startX);
    s << indent << "startY: ";
    Printer<float>::stream(s, indent + "  ", v.startY);
    s << indent << "endFloor: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.endFloor);
    s << indent << "endX: ";
    Printer<float>::stream(s, indent + "  ", v.endX);
    s << indent << "endY: ";
    Printer<float>::stream(s, indent + "  ", v.endY);
  }
};


} // namespace message_operations
} // namespace ros

#endif // TASKALLOCATOR_MESSAGE_INSTRUCTION_H

