/* Auto-generated by genmsg_cpp for file /nishome/gcerna/ros/rosbuild_ws/taskallocator/msg/Task.msg */
#ifndef TASKALLOCATOR_MESSAGE_TASK_H
#define TASKALLOCATOR_MESSAGE_TASK_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"
#include "taskallocator/Instruction.h"

namespace taskallocator
{
template <class ContainerAllocator>
struct Task_ {
  typedef Task_<ContainerAllocator> Type;

  Task_()
  : header()
  , instructions()
  {
  }

  Task_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , instructions(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef std::vector< ::taskallocator::Instruction_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::taskallocator::Instruction_<ContainerAllocator> >::other >  _instructions_type;
  std::vector< ::taskallocator::Instruction_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::taskallocator::Instruction_<ContainerAllocator> >::other >  instructions;


  typedef boost::shared_ptr< ::taskallocator::Task_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::taskallocator::Task_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Task
typedef  ::taskallocator::Task_<std::allocator<void> > Task;

typedef boost::shared_ptr< ::taskallocator::Task> TaskPtr;
typedef boost::shared_ptr< ::taskallocator::Task const> TaskConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::taskallocator::Task_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::taskallocator::Task_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace taskallocator

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::taskallocator::Task_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::taskallocator::Task_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::taskallocator::Task_<ContainerAllocator> > {
  static const char* value() 
  {
    return "23298917be122f4030b24018b6283f17";
  }

  static const char* value(const  ::taskallocator::Task_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x23298917be122f40ULL;
  static const uint64_t static_value2 = 0x30b24018b6283f17ULL;
};

template<class ContainerAllocator>
struct DataType< ::taskallocator::Task_<ContainerAllocator> > {
  static const char* value() 
  {
    return "taskallocator/Task";
  }

  static const char* value(const  ::taskallocator::Task_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::taskallocator::Task_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
Instruction[] instructions\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: taskallocator/Instruction\n\
Header header\n\
\n\
#determines type of instruction\n\
bool reqsHumanHelp\n\
\n\
#standardized set of descriptors for different human interactions (eventually)\n\
#extraneous if reqsHumanHelp is false\n\
#not yet implemented (only goto is right now) \n\
string helpDescriptor\n\
\n\
#all fields below are only for goto commands\n\
#extraneous if reqsHumanHelp is true\n\
uint32 startFloor\n\
float32 startX\n\
float32 startY\n\
\n\
uint32 endFloor\n\
float32 endX\n\
float32 endY\n\
\n\
";
  }

  static const char* value(const  ::taskallocator::Task_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::taskallocator::Task_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::taskallocator::Task_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::taskallocator::Task_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.instructions);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Task_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::taskallocator::Task_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::taskallocator::Task_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "instructions[]" << std::endl;
    for (size_t i = 0; i < v.instructions.size(); ++i)
    {
      s << indent << "  instructions[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::taskallocator::Instruction_<ContainerAllocator> >::stream(s, indent + "    ", v.instructions[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // TASKALLOCATOR_MESSAGE_TASK_H

