"""autogenerated by genpy from taskallocator/Bid.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import taskallocator.msg
import std_msgs.msg

class Bid(genpy.Message):
  _md5sum = "d550354f9161d53878b35fcb15499a4f"
  _type = "taskallocator/Bid"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """Header header
Instruction inst
float32 bidCost

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.secs: seconds (stamp_secs) since epoch
# * stamp.nsecs: nanoseconds since stamp_secs
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: taskallocator/Instruction
Header header
uint32 ID
uint32 startFloor
float32 startX
float32 startY
uint32 endFloor
float32 endX
float32 endY

"""
  __slots__ = ['header','inst','bidCost']
  _slot_types = ['std_msgs/Header','taskallocator/Instruction','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,inst,bidCost

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Bid, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.inst is None:
        self.inst = taskallocator.msg.Instruction()
      if self.bidCost is None:
        self.bidCost = 0.
    else:
      self.header = std_msgs.msg.Header()
      self.inst = taskallocator.msg.Instruction()
      self.bidCost = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_3I.pack(_x.inst.header.seq, _x.inst.header.stamp.secs, _x.inst.header.stamp.nsecs))
      _x = self.inst.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_2I2fI3f.pack(_x.inst.ID, _x.inst.startFloor, _x.inst.startX, _x.inst.startY, _x.inst.endFloor, _x.inst.endX, _x.inst.endY, _x.bidCost))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.inst is None:
        self.inst = taskallocator.msg.Instruction()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.inst.header.seq, _x.inst.header.stamp.secs, _x.inst.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.inst.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.inst.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 32
      (_x.inst.ID, _x.inst.startFloor, _x.inst.startX, _x.inst.startY, _x.inst.endFloor, _x.inst.endX, _x.inst.endY, _x.bidCost,) = _struct_2I2fI3f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_3I.pack(_x.inst.header.seq, _x.inst.header.stamp.secs, _x.inst.header.stamp.nsecs))
      _x = self.inst.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_2I2fI3f.pack(_x.inst.ID, _x.inst.startFloor, _x.inst.startX, _x.inst.startY, _x.inst.endFloor, _x.inst.endX, _x.inst.endY, _x.bidCost))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.inst is None:
        self.inst = taskallocator.msg.Instruction()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.inst.header.seq, _x.inst.header.stamp.secs, _x.inst.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.inst.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.inst.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 32
      (_x.inst.ID, _x.inst.startFloor, _x.inst.startX, _x.inst.startY, _x.inst.endFloor, _x.inst.endX, _x.inst.endY, _x.bidCost,) = _struct_2I2fI3f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_2I2fI3f = struct.Struct("<2I2fI3f")
_struct_3I = struct.Struct("<3I")
